In [7]:
from tbMethod import *
import pandas as pd

# Obtaining training data
The following code runs through the 2002-2021 NFL seasons and obtains offensive and defensive team data from each regular season. Then, it downloads the dataframe as a local csv.

In [3]:
dataframes = []
for i in range(2002, 2022):
    df_temp = tableMethod(year=i, input_id='team_stats', url2='https://www.pro-football-reference.com/years/{}/')
    df_temp['Year'] = i
    df_temp2 = df_temp[0:32]
    dataframes.append(df_temp2)
df_off = pd.concat(dataframes)
df_off

,Tm,G,PF,Yds,Ply,Y/P,TO,FL,1stD,Cmp,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,Year
0,Kansas City Chiefs,16,467,6000,965,6.2,15,2,343,292,...,26,5.1,140,75,700,24,42.7,7.9,145.45,2002
1,Oakland Raiders,16,450,6237,1069,5.8,19,9,366,418,...,21,4.3,113,129,1094,27,42.7,9.4,123.35,2002
2,New Orleans Saints,16,432,5205,1001,5.2,30,15,291,291,...,16,4.1,91,119,911,31,38.5,14.6,-77.44,2002
3,Philadelphia Eagles,16,415,5604,1073,5.2,24,13,311,318,...,15,4.5,124,111,897,23,36.0,12.0,-15.34,2002
4,Atlanta Falcons,16,402,5535,1038,5.3,27,15,316,268,...,23,4.5,123,105,931,30,38.6,13.2,38.40,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,New York Jets,17,310,5208,1036,5.0,27,7,310,357,...,14,4.4,87,103,860,28,29.4,14.4,-32.71,2021
28,Carolina Panthers,17,304,5081,1106,4.6,29,8,322,348,...,17,4.0,118,107,864,30,29.2,14.9,-92.10,2021
29,Houston Texans,17,280,4727,1010,4.7,22,7,266,354,...,8,3.4,77,114,978,27,26.6,11.2,-74.29,2021
30,New York Giants,17,258,4884,1050,4.7,30,10,299,351,...,8,4.0,90,88,674,38,27.5,15.9,-100.13,2021
31,Jacksonville Jaguars,17,253,5191,1028,5.0,29,12,304,361,...,13,4.5,92,104,856,34,26.4,15.7,-42.52,2021

In [4]:
def_dataframes = []
for i in range(2002, 2022):
    df_temp = tableMethod(year=i, input_id='team_stats', url2='https://www.pro-football-reference.com/years/{}/opp.htm')
    df_temp['Year'] = i
    df_temp2 = df_temp[0:32]
    def_dataframes.append(df_temp2)
df_def = pd.concat(def_dataframes)
df_def

,Tm,G,PA,Yds,Ply,Y/P,TO,FL,1stD,Cmp,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,Year
0,Tampa Bay Buccaneers,16,196,4044,963,4.2,38,7,236,259,...,8,3.8,79,93,749,26,17.8,18.3,284.70,2002
1,Philadelphia Eagles,16,241,4754,1009,4.7,38,23,272,333,...,5,4.3,83,112,969,29,20.6,18.0,173.69,2002
2,New York Giants,16,279,4949,985,5.0,25,14,266,311,...,12,4.5,87,120,897,17,27.0,12.4,63.16,2002
3,Miami Dolphins,16,301,4656,974,4.8,30,9,285,294,...,9,3.8,86,106,826,37,30.3,14.4,117.76,2002
4,Carolina Panthers,16,302,4646,1022,4.5,33,16,271,293,...,12,3.7,95,98,782,21,25.5,14.2,123.24,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,Jacksonville Jaguars,17,457,6002,1068,5.6,9,2,351,377,...,22,4.3,124,104,879,29,45.3,5.2,-154.57,2021
28,Atlanta Falcons,17,459,6194,1114,5.6,20,8,383,391,...,19,4.3,143,118,956,26,44.7,11.2,-136.74,2021
29,Los Angeles Chargers,17,459,6122,1103,5.6,21,10,383,357,...,22,4.6,144,99,835,40,45.3,11.2,-122.86,2021
30,Detroit Lions,17,467,6456,1092,5.9,19,8,372,359,...,19,4.4,135,87,818,26,47.8,10.6,-176.03,2021
31,New York Jets,17,504,6760,1145,5.9,14,7,401,401,...,28,4.5,129,84,814,38,48.9,7.4,-193.85,2021

In [5]:
df_off.to_csv("NFL-offense-test-data.csv")

In [6]:
df_def.to_csv("NFL-defense-test-data.csv")

# Obtaining test data
The code below obtains the offensive and defensive data of the current regular season.

In [8]:
df_2022_off = tableMethod(year=2022, input_id='team_stats', url2='https://www.pro-football-reference.com/years/{}/')
df_2022_def = tableMethod(year=2022, input_id='team_stats', url2='https://www.pro-football-reference.com/years/{}/opp.htm')

In [19]:
df_2022_off

,Tm,G,PF,Yds,Ply,Y/P,TO,FL,1stD,Cmp,...,Yds,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP
0,Kansas City Chiefs,17,496,7032,1094,6.4,23,11,408,435,...,1970,18,4.7,105,87,838,31,46.4,10.1,239.21
1,Philadelphia Eagles,17,477,6614,1124,5.9,19,10,385,350,...,2509,32,4.6,161,90,682,29,42.5,10.2,175.61
2,Dallas Cowboys,17,467,6034,1114,5.4,23,5,347,355,...,2298,24,4.3,129,104,842,24,41.5,10.8,93.24
3,Buffalo Bills,16,455,6361,1037,6.1,27,13,367,361,...,2232,15,5.2,128,92,709,27,45.0,15.2,156.35
4,Detroit Lions,17,453,6460,1092,5.9,15,8,376,383,...,2179,23,4.5,114,90,773,34,43.2,8.0,162.04
5,San Francisco 49ers,17,450,6216,1047,5.9,17,8,347,338,...,2360,20,4.7,132,94,730,27,41.4,9.1,142.90
6,Minnesota Vikings,17,424,6145,1123,5.5,23,8,382,448,...,1661,18,4.1,93,88,689,45,36.0,11.7,75.78
7,Cincinnati Bengals,16,418,5768,1053,5.5,18,6,357,418,...,1528,14,3.8,96,81,623,40,41.5,9.7,120.83
8,Seattle Seahawks,17,407,5976,1044,5.7,23,11,346,399,...,2042,12,4.8,106,106,854,34,40.6,11.2,57.19
9,Jacksonville Jaguars,17,404,6075,1072,5.7,22,13,352,394,...,2116,16,4.7,114,90,674,30,39.2,12.2,95.22
10,Miami Dolphins,17,397,6197,1009,6.1,21,6,342,368,...,1686,12,4.3,93,111,881,29,38.8,11.8,94.62
11,Las Vegas Raiders,17,395,5993,1049,5.7,21,4,343,359,...,2059,12,4.8,122,113,932,28,42.4,12.2,74.09
12,Los Angeles Chargers,17,391,6108,1154,5.3,19,9,352,485,...,1524,15,3.8,93,81,635,27,38.1,9.5,72.46
13,Green Bay Packers,17,370,5745,1051,5.5,22,10,334,364,...,2113,12,4.6,116,89,747,32,36.2,11.3,68.90
14,Atlanta Falcons,17,365,5417,1011,5.4,21,12,330,257,...,2718,17,4.9,152,68,594,30,39.5,11.4,73.69
15,New York Giants,17,365,5676,1089,5.2,16,10,352,346,...,2519,21,4.8,150,106,827,32,37.3,7.3,63.32
16,New England Patriots,17,364,5348,1006,5.3,23,9,288,358,...,1812,12,4.3,98,104,841,24,32.8,12.0,-25.81
17,Cleveland Browns,17,361,5934,1116,5.3,21,9,350,335,...,2490,19,4.7,142,102,865,26,34.6,11.2,58.03
18,Baltimore Ravens,17,350,5760,1052,5.5,21,8,337,300,...,2720,14,5.2,167,82,678,21,38.9,11.7,49.94
19,Carolina Panthers,17,347,5206,976,5.3,21,8,281,267,...,2210,16,4.6,119,104,862,24,35.3,9.6,-5.06
20,Arizona Cardinals,17,340,5499,1144,4.8,25,8,326,433,...,1873,15,4.3,115,118,916,22,32.1,12.8,-36.27
21,New Orleans Saints,17,330,5674,1015,5.6,25,11,305,338,...,1982,12,4.3,103,99,841,21,31.7,12.9,17.30
22,Chicago Bears,17,326,5233,993,5.3,25,10,278,223,...,3014,18,5.4,148,80,754,21,34.3,12.7,-7.14
23,Washington Commanders,17,321,5615,1140,4.9,23,7,339,344,...,2143,9,4.0,124,92,805,31,29.4,11.7,-24.27
24,Tampa Bay Buccaneers,17,313,5894,1159,5.1,22,12,346,499,...,1308,5,3.4,79,99,793,27,32.0,10.3,3.03
25,Pittsburgh Steelers,17,308,5488,1109,4.9,19,5,345,364,...,2077,16,4.2,129,94,711,27,35.0,9.6,42.17
26,Los Angeles Rams,17,307,4769,1001,4.8,23,8,293,347,...,1661,15,4.0,89,76,655,23,33.5,13.1,-7.51
27,Tennessee Titans,17,298,5045,992,5.1,23,12,277,285,...,2131,16,4.4,104,111,956,20,27.9,10.5,-27.22
28,New York Jets,17,296,5409,1074,5.0,23,9,294,357,...,1686,13,4.2,79,91,866,24,29.9,11.9,-47.59
29,Houston Texans,17,289,4820,1015,4.7,28,9,277,352,...,1476,7,3.7,90,88,644,28,28.8,13.6,-120.05
30,Indianapolis Colts,17,289,5298,1103,4.8,34,14,310,398,...,1866,8,4.3,91,89,794,26,29.2,16.9,-109.92
31,Denver Broncos,17,287,5527,1078,5.1,24,9,300,345,...,1935,11,4.4,105,113,970,29,28.6,10.6,-41.62
32,Avg Team,,370.6,5760.5,1066.8,5.4,22.2,9.1,333.3,362.7,...,2059.3,15.2,4.5,115.2,94.8,780.7,27.9,36.2,11.3,46.4
33,League Total,,11860,184336,34136,5.4,710,292,10666,11605,...,65898,487,4.5,3686,3032,24981,893,36.2,11.3,
34,Avg Tm/G,,21.9,340.1,63.0,5.4,1.3,0.5,19.7,21.4,...,121.6,0.9,4.5,6.8,5.6,46.1,1.6,36.2,11.3,

In [17]:
df_2022_off.to_csv("NFL-offense-testing-data.csv")

In [18]:
df_2022_def.to_csv("NFL-defense-testing-data.csv")

# Break here for now!

In [37]:
df_off = df_off.sort_values(by=['Tm', 'Year']).reset_index()
df_off = df_off.add_prefix('off_')
df_def = df_def.sort_values(by=['Tm', 'Year']).reset_index()
df_def = df_def.add_prefix('def_')

KeyError: 'Tm'

In [35]:
df_test = pd.merge(df_off, df_def, left_on=['off_Tm', 'off_Year'], right_on=['def_Tm', 'def_Tm'])
df_test

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

In [41]:
df_off

,Tm,G,PF,Yds,Ply,Y/P,TO,FL,1stD,Cmp,...,TD,Y/A,1stD,Pen,Yds,1stPy,Sc%,TO%,EXP,Year
0,Kansas City Chiefs,16,467,6000,965,6.2,15,2,343,292,...,26,5.1,140,75,700,24,42.7,7.9,145.45,2002
1,Oakland Raiders,16,450,6237,1069,5.8,19,9,366,418,...,21,4.3,113,129,1094,27,42.7,9.4,123.35,2002
2,New Orleans Saints,16,432,5205,1001,5.2,30,15,291,291,...,16,4.1,91,119,911,31,38.5,14.6,-77.44,2002
3,Philadelphia Eagles,16,415,5604,1073,5.2,24,13,311,318,...,15,4.5,124,111,897,23,36.0,12.0,-15.34,2002
4,Atlanta Falcons,16,402,5535,1038,5.3,27,15,316,268,...,23,4.5,123,105,931,30,38.6,13.2,38.40,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,New York Jets,17,310,5208,1036,5.0,27,7,310,357,...,14,4.4,87,103,860,28,29.4,14.4,-32.71,2021
28,Carolina Panthers,17,304,5081,1106,4.6,29,8,322,348,...,17,4.0,118,107,864,30,29.2,14.9,-92.10,2021
29,Houston Texans,17,280,4727,1010,4.7,22,7,266,354,...,8,3.4,77,114,978,27,26.6,11.2,-74.29,2021
30,New York Giants,17,258,4884,1050,4.7,30,10,299,351,...,8,4.0,90,88,674,38,27.5,15.9,-100.13,2021
31,Jacksonville Jaguars,17,253,5191,1028,5.0,29,12,304,361,...,13,4.5,92,104,856,34,26.4,15.7,-42.52,2021

In [42]:
df_def

,def_Tm,def_G,def_PA,def_Yds,def_Ply,def_Y/P,def_TO,def_FL,def_1stD,def_Cmp,...,def_TD,def_Y/A,def_1stD,def_Pen,def_Yds,def_1stPy,def_Sc%,def_TO%,def_EXP,def_Year
28,Arizona Cardinals,16,417,6020,1046,5.8,25,8,335,335,...,17,4.4,117,111,969,22,36.4,12.3,-93.81,2002
31,Arizona Cardinals,16,452,5504,993,5.5,23,10,326,311,...,17,4.0,120,86,754,22,36.8,12.4,-2.10,2003
11,Arizona Cardinals,16,322,5141,993,5.2,30,15,282,271,...,12,4.7,101,139,1121,28,27.1,14.8,162.40,2004
25,Arizona Cardinals,16,387,4729,936,5.1,26,11,272,301,...,22,4.0,83,103,819,31,30.3,13.1,118.27,2005
28,Arizona Cardinals,16,389,5591,1018,5.5,33,17,331,321,...,16,4.1,114,95,815,31,37.6,18.2,148.96,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,Washington Redskins,16,379,6090,1010,6.0,27,16,329,354,...,10,4.8,103,112,955,24,35.4,14.9,-55.35,2015
18,Washington Redskins,16,383,6046,1050,5.8,21,8,368,387,...,19,4.5,109,100,1023,34,38.5,11.8,-32.66,2016
27,Washington Redskins,16,388,5566,1045,5.3,23,7,307,306,...,13,4.5,105,100,887,31,35.9,11.8,120.68,2017
14,Washington Redskins,16,359,5654,996,5.7,26,11,330,362,...,12,4.5,109,102,791,24,35.1,14.6,-87.52,2018
26,Washington Redskins,16,435,6162,1079,5.7,22,9,354,371,...,14,4.7,120,94,805,34,42.0,11.9,-132.83,2019

In [19]:
df_super_bowl_winners = pd.read_csv('super-bowl-winners.csv')
df_super_bowl_winners

,Date,SB,Winner,Pts,Loser,Pts.1,MVP,Stadium,City,State
0,Feb 13 2022,LVI (56),Los Angeles Rams,23,Cincinnati Bengals,20,Cooper Kupp,SoFi Stadium,Inglewood,California
1,Feb 7 2021,LV (55),Tampa Bay Buccaneers,31,Kansas City Chiefs,9,Tom Brady,Raymond James Stadium,Tampa,Florida
2,Feb 2 2020,LIV (54),Kansas City Chiefs,31,San Francisco 49ers,20,Patrick Mahomes,Hard Rock Stadium,Miami Gardens,Florida
3,Feb 3 2019,LIII (53),New England Patriots,13,Los Angeles Rams,3,Julian Edelman,Mercedes-Benz Stadium,Atlanta,Georgia
4,Feb 4 2018,LII (52),Philadelphia Eagles,41,New England Patriots,33,Nick Foles,U.S. Bank Stadium,Minneapolis,Minnesota
5,Feb 5 2017,LI (51),New England Patriots,34,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas
6,Feb 7 2016,50,Denver Broncos,24,Carolina Panthers,10,Von Miller,Levi's Stadium,Santa Clara,California
7,Feb 1 2015,XLIX (49),New England Patriots,28,Seattle Seahawks,24,Tom Brady,University of Phoenix Stadium,Glendale,Arizona
8,Feb 2 2014,XLVIII (48),Seattle Seahawks,43,Denver Broncos,8,Malcolm Smith,MetLife Stadium,East Rutherford,New Jersey
9,Feb 3 2013,XLVII (47),Baltimore Ravens,34,San Francisco 49ers,31,Joe Flacco,Mercedes-Benz Superdome,New Orleans,Louisiana
10,Feb 5 2012,XLVI (46),New York Giants,21,New England Patriots,17,Eli Manning,Lucas Oil Stadium,Indianapolis,Indiana
11,Feb 6 2011,XLV (45),Green Bay Packers,31,Pittsburgh Steelers,25,Aaron Rodgers,Cowboys Stadium,Arlington,Texas
12,Feb 7 2010,XLIV (44),New Orleans Saints,31,Indianapolis Colts,17,Drew Brees,Sun Life Stadium,Miami Gardens,Florida
13,Feb 1 2009,XLIII (43),Pittsburgh Steelers,27,Arizona Cardinals,23,Santonio Holmes,Raymond James Stadium,Tampa,Florida
14,Feb 3 2008,XLII (42),New York Giants,17,New England Patriots,14,Eli Manning,University of Phoenix Stadium,Glendale,Arizona
15,Feb 4 2007,XLI (41),Indianapolis Colts,29,Chicago Bears,17,Peyton Manning+,Dolphin Stadium,Miami Gardens,Florida
16,Feb 5 2006,XL (40),Pittsburgh Steelers,21,Seattle Seahawks,10,Hines Ward,Ford Field,Detroit,Michigan
17,Feb 6 2005,XXXIX (39),New England Patriots,24,Philadelphia Eagles,21,Deion Branch,Alltel Stadium,Jacksonville,Florida
18,Feb 1 2004,XXXVIII (38),New England Patriots,32,Carolina Panthers,29,Tom Brady,Reliant Stadium,Houston,Texas
19,Jan 26 2003,XXXVII (37),Tampa Bay Buccaneers,48,Oakland Raiders,21,Dexter Jackson,Qualcomm Stadium,San Diego,California